# Generated by Django 4.1.3 on 2022-11-05 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('Break', 'Break'), ('Cabrio', 'Cabrio'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], max_length=20)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('engine', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=20)),
                ('horsepower', models.IntegerField()),
                ('cylinder_capacity', models.FloatField(blank=True, null=True)),
                ('gearbox', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('transmission', models.CharField(choices=[('4x4', '4x4'), ('Rear', 'Rear'), ('Front', 'Front')], max_length=20)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Blue', 'Blue'), ('Green', 'Green'), ('Grey', 'Grey'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow'), ('Other Color', 'Other Color')], max_length=20)),
                ('fabrication_year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
