# Generated by Django 4.1.3 on 2022-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_model_listing_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='kilometers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
