# Generated by Django 4.1.3 on 2022-11-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='kilometers',
            new_name='mileage',
        ),
    ]
