# Generated by Django 4.1.3 on 2022-11-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_name',
            field=models.CharField(default=124, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_phone_number',
            field=models.IntegerField(default=234, max_length=30),
            preserve_default=False,
        ),
    ]
