# Generated by Django 4.1.3 on 2022-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_seller_name_listing_seller_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='seller_phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
